database_path: 'sqlite:///db.sqlite3'
screen_names:
  # kinpri
  - yanpri_pr
  # prettyrhythm
  - hishidamasakazu
  - sayaka_toda_
  - shinohba
  - tsubofumi
  - katokatodai
  - kenkenhappy
  - torauman # kojikoji
  # prizmmy
  - prizmmyofficial
  - prizmmy_mia
  - prizmmy_karin_
  - prizmmy_hina_
  - miakusakabe_official
  - 017_reina_017
  # iris
  - seriko_is_no.1
  - azk_s811
  # rilurilu
  - rilurilu_segatoys
